server.port: 8081

chaos.monkey:
  enabled: true
  watcher:
    controller: false
    restController: true
    service: false
    repository: false
    component: false
  assaults:
    latencyActive: true
    latencyRangeStart: 1000
    latencyRangeEnd: 5000

util.timer.enabled: true

management:
  endpoint.chaosmonkey.enabled: true
  endpoints.web.exposure.include:
    - health
    - chaosmonkey
springdoc:
  swagger-ui.path: /swagger
  show-actuator: true
